#pragma once
void test_array();
void test_string();
void test_vector();
void test_matrix();
void test_real();
void test_linear_algebra();
void test_ui();
void test_set();
void test_file();
void test_fileset();
void test_web_server();
void test_structured_file();
